### ISSUE TITLE
Balancing Act: Enabling Personal Growth or Enabling Performance Measurement?

### ISSUE THREAD

**Issue by michaelnoonan** [Readify/madskillz#32]
Quoting @andrewabest from https://github.com/Readify/madskillz/issues/28#issuecomment-107793584, I think this is worth promoting to its own discussion since this has been a hot and interesting topic of conversation in QLD.

> To your point of ensuring that we have an equal yardstick when measuring someones capabilities - this is where the duality of MadSkillz kicks in. It needs to both support the needs of the consulting pool, allowing them to communicate openly and freely as is needed to drive growth, and the needs of our HR department when they need to decide whether people are performing up to expectations, whether people deserve promotions, and how much people should be paid. The more of a 'measurement' tool it becomes, the less of a 'growth' tool it will be, as people won't be as honest and open in discussing the points if it is being used to 'measure' them to judge their bottom line.

> I believe the current approach of gathering evidence from the retrospectives (which will vary a lot from consultant to consultant) and mixing this with the leadership groups opinion should lead to a fairly equitable judgement of a given persons contribution to Readify.

Are there some principles we can establish to maintain a happy balance between "creating a safe-zone for retrospective conversations that encourage personal growth" and "using it to make decisions based on a person's contribution to Readify"?

**Comment by MooseMagnet** [comment]
I'm not opposed to MadSkillz being used as part of performance assessment.

MadSkillz epitomizes the various roles within Readify; It is a well-intentioned, peer-reviewed and -refined criteria by which we have already begun to assess ourselves and help quantify our value.

I've always thought that pay-grade should be proportionate to performance / value to the company. I get the feeling we've all worked with people in the past whose capabilities / overall investment in the business were less than our own but whose payslips had a bigger number on them. It's frustrating, but more than that it's just... wrong.

At the end of the day, I acknowledge my (at least partial) responsibility to the company whose money I'm accepting and also to my fellow employees to participate in a fair remuneration scheme. If my remuneration increases (or decreases...) proportionately with my value to the company then it's a good system in my view.

Rewarding the wrong people is a great way to increase turnover... Given that great (no, AMAZING) developers are integral to Readify's position, I would expect that there's some degree of fear of underpaying people, regardless of how many "needs coaching"s are on their review. Amazing developers are hard to come by, and surely harder to re-acquire once they move on.

The problem seems to be a lack of trust that our honesty (read: humility) will be punished rather than rewarded. 
I've only been here for a short while, but I don't expect that anyone in QLD could really get away with being dishonest about their capabilities anyway. Maybe I'm wrong, but for the most part the leadership team seems to be fairly cluey about who's strong in what areas. In fact, there seems to be a decent collective understanding of that throughout the team in general.
Readify enjoys much success and renown, and that's undoubtedly because it holds it's employees accountable to delivery at a high standard. 
The point of saying all this is to turn it around a little with a suggestion:
Our value to the company is already being assessed.

Is the current performance metric better or worse than MadSkillz?

Having only really caught a glimpse of the previous method (skills matrix), my opinion is somewhat naive, but I feel like MadSkillz is a step up... I'd prefer to use it over the alternative.


I think if MadSkillz were to be used as a basis for an assessment of value in relation to Readify's requirements (which it basically represents), and in addition to a personalised review performed by relevant (i.e. familiar) members of the leadership team, we could have a balanced system which facilitates professional growth and fair remuneration.

**Comment by andrewabest** [comment]
I'm a little surprised that what I thought would be a potentially contentious discussion point has not elicited more comment. Is no one out side of Queensland worried about the potential conflict of interest posed? Or is the general consensus that there is little to worry about, and that we have enough maturity and trust to have open, honest conversations without fear of how they might affect our personal bottom line?

I'd love to solicit some opinions in here from our interstate leaders - @robdmoore @rbanks54 @quinten-miller?

**Comment by chriswithpants** [comment]
I think the fact that someone has privately suggested making such comments to be a career limiting move explains both the absence of feedback on this topic as well as the concerns some people have.

**Comment by uglybugger** [comment]
I don't really have much to say on this. My personal observation has been that MadSkillz has already departed so far from its original intent that it's become merely yet another ranking framework. Its value was in the open, honest and safe conversations that it catalysed - and then we attached money to it and *everyone's behaviour towards it changed*.

**Comment by robdmoore** [comment]
I've been a fly on the wa for this conversation. I've agreed with most of what has been said and didn't feel there was much to add.

I don't want to put words in the mouths of my colleagues, but it's fair to say that team WA has always rallied against tying pay to performance (in particular Demming has some important stuff to say against this as my main man Bobby Lat will point out).?

**Comment by robdmoore** [comment]
(Oops sorry about that - writing this in the train and it moved suddenly and I tapped the wrong button!!)

I've been a fly on the wa(ll - hi Ben!) for this conversation. I've agreed with most of what has been said and didn't feel there was much to add.

I don't want to put words in the mouths of my colleagues, but it's fair to say that team WA has always rallied against tying pay to performance (in particular Demming has some important stuff to say against this as my main man Bobby Lat will point out). I think removing the link from performance to the bonus was a huge first step in this regard,

With respect to payrises I'm not 100% sure how they are done this year, so I can't comment on how this affects that; perhaps that in itself is an issue in the fact that people can't be truthful with this process if they aren't sure if it will or won't have an impact on their salary? I hope that's not the case, but who knows.

With respect to promotions, I think that given that the consultants are the ones having a collaborative dialogue and peer-reviewed contribution process I feel mad skillz is an excellent description of what it means to be in each role! There is one problem I see in the way we currently do it though - we rank against your current level and wait until you are outstanding or no brainer in everything. I think it makes
Much more sense to combine this with a rating against the next level - Id expect someone that wants a promotion to be stepping outside their current role and be at a maturing on at least some of the next level. To that end I think that mad skillz is a fair way of assessing what level you are at.

In saying all that, it's obviously important that there is an element of trust because if you can't retrospect yourself fairly against the criteria then no only will that impact your ability to get that promotion, but (more importantly?) it impedes your ability to have an accurate idea of what areas you need to improve on.

The interesting thing is, to have a proper retrospective you need outside points of view - it's impossible to know completely how you do at everything let alone come up with improvements ideas by yourself. I had my end of year retro on Friday and I found the conversation (in this case with an LC and my state manager) to be incredibly valuable and fruitful. So, the point in making here is that we need to have these conversations with our peers and the great thing is that we are since that's the way it's been implemented. Given that LCs and PCs are responsible for the feedback process (ensuring it happens and ensuring that people get a fair and consistent conversation - be it they do it themselves or assist team members to do each other's retros), and given that (hopefully) the LCs and PCs in each state are respected and trusted by the consulting pool I think we are in a good position.

I'm not saying it's perfect, but I think until we brainstorm a better approach I'm happy that this is the best idea and the best impentation I've seen to date for giving and receiving feedback and I hope that the consulting pool has the trust (and the senior leadership teams repay that trust by being fair and using this system in good faith) so that it can work successfully.

**Comment by mjhilton** [comment]
> The more of a 'measurement' tool it becomes, the less of a 'growth' tool it will be, as people won't be as honest and open in discussing the points if it is being used to 'measure' them to judge their bottom line

As a scientifically minded person, my view is that if I want to grow then I necessarily need to:

* Measure where I am now
* Compare that to where I want to be
* Create a plan to fill the gaps
* Fulfil the plan, then repeat

That is - measurement and growth are inextricably linked. The fact that we get to use the same benchmark for our performance review is awesome and unique.

Readify pays me well enough that my goals and drivers aren't dollars. This means that I can pursue growth, development and learning, with increased pay being a by-product of my increase in value provided through this growth - not the goal in and of itself. If my goal was money, I'd be contracting to a bank right now. And hating life.

> it's become merely yet another ranking framework. Its value was in the open, honest and safe conversations that it catalysed - and then we attached money to it and everyone's behaviour towards it changed.

I'd like to think that Readifarians are the kind of people who are able to have open, honest and transparent discussions regardless of the forum - whether this is in an ad-hoc mentoring arrangement with someone I already trust, in a quarterly retro with someone I've only known a few months, or in an end-of year review with any of my state leadership team.

We've been given the opportunity to define our roles, how we want to be measured, at what cadence... I'm at a loss to understand how much more could practically be done to build trust and give opportunity for us to define how we want things to work. Without any alternatives suggested, I'm in agreement with @robdmoore:

> until we brainstorm a better approach I'm happy that this is the best idea and the best impentation I've seen to date for giving and receiving feedback and I hope that the consulting pool has the trust (and the senior leadership teams repay that trust by being fair and using this system in good faith) so that it can work successfully.

**Comment by rbanks54** [comment]
@andrewabest Responding to the request for comment :-)

> Or is the general consensus that there is little to worry about, and that we have enough maturity and trust to have open, honest conversations without fear of how they might affect our personal bottom line?

This. :+1: 

I assume the conflict of interest is that people will somehow "game the system" to get rewards they haven't genuinely/fairly earned or that people won't get the rewards they deserve because they somehow have a skill/behaviour but aren't able to show it?

I don't see it happening. Here's why.

* Readify values and invests in people. It's what the business is founded on. Having a loosely defined set of expectations for each role is critical if we're going to help people win at their current role and know what they need to do for the next one.
* Mad Skillz allows those doing the job to define what those skillz are. A way for us to have autonomy about the height of the bar we hold both ourselves and our peers to.
* Salary is not tied to Mad Skillz - it's tied to the position you hold. Yes, Mad Skillz is used as part of the promotion process, but it's not the only thing (e.g. *"High ethical standards and loyalty to Readify"*)
* Bonuses aren't tied to MadSkillz, see the [Bonus Scheme](https://readify.sharepoint.com/the-way-we-work/Pages/Profit-based%20Bonus%20Scheme.aspx) info on the intranet. While there is obviously some commonality, the bonus assessment process is not the same as a retro.

Even if there was a tight link between money and MadSkillz, I wouldn't have a problem. Conversations around Mad Skillz are objective, affirmative and evidence/example based; not subjective, hand-wavy, or personality based.

Being asked "Can you point to specific examples that show this particular Mad Skill?" should increase the desire for people to be honest and open about what they've done. If someone can't show any examples of a skill, it means we've identified a gap that needs maturing/coaching or that the opportunity hasn't arisen yet and we'll actively find an opportunity for them to prove themselves. Until there's evidence, it's just one opinion versus another.

Also, as @mjhilton pointed out, without any form of assessment how do we set a direction for growth? The fear, and I'll use that term if I may as I think it is the subtext to the question; the fear that people will try to game mad skillz is overlooking a few things:

* If we think a skill or behaviour is missing from the list, we can add it.
* Mad Skillz helps ensure that any attempt at gaming actually encourages the behaviours we want from each other

**Comment by andrewabest** [comment]
@rbanks54 I wasn't alluding to gaming the system at all, more that people may fear being completely honest around their shortcomings if that honesty costs them potential money.

> Salary is not tied to Mad Skillz - it's tied to the position you hold
This is not entirely accurate, salary is based on position and _performance_, which is measured at least in part via madskillz. So while your salary is primarily affected by position, it is also adjusted yearly based in part on your performance measured via madskillz.

Performance based pay discussions aside, I think we have enough representative opinions in this thread now to provide food for thought. If we want to discuss it further I'd suggest we start a dialog with our representative leadership groups and the HR team to more clearly define and weigh the issue.
